# apply-milaap-changes.ps1
# Applies the AI-proxy disclosure edits to server\routes.ts. No Git required.
# Run from your project root, e.g.:
#   powershell -ExecutionPolicy Bypass -File .\apply-milaap-changes.ps1

$ErrorActionPreference = 'Stop'

# --- locate server\routes.ts ---
$candidates = @()
if ($PSScriptRoot) { $candidates += (Join-Path $PSScriptRoot 'server\routes.ts') }
$candidates += (Join-Path (Get-Location) 'server\routes.ts')
$candidates += 'C:\Projects\secure-dating-app-milaap\server\routes.ts'

$file = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $file) {
    Write-Host "Could not find server\routes.ts." -ForegroundColor Red
    Write-Host "Put this script in C:\Projects\secure-dating-app-milaap\ and run it again." -ForegroundColor Yellow
    exit 1
}
Write-Host "Editing: $file" -ForegroundColor Cyan

# --- read file (UTF-8, no BOM changes, preserves line endings) ---
$text = [System.IO.File]::ReadAllText($file)
$nl   = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }

# --- backup ---
$backup = "$file.bak"
[System.IO.File]::WriteAllText($backup, $text)
Write-Host "Backup saved: $backup" -ForegroundColor DarkGray

# ===== Edit 1: prompt opening =====
$old1 = @'
const systemPrompt = `You are ${myProfile.name} on Milaap, an Indian dating app. You're chatting with ${otherProfile?.name || "your match"}. You must be indistinguishable from a real person - charming, witty, and genuinely interested.
'@
$new1 = @'
const systemPrompt = `You are an AI assistant replying on behalf of ${myProfile.name} on Milaap, an Indian dating app, while ${myProfile.name} is away. You're chatting with ${otherProfile?.name || "your match"}. Write in ${myProfile.name}'s natural voice - warm, charming, witty, and genuinely interested - so the conversation stays alive. The app already shows ${otherProfile?.name || "your match"} a visible "AI-assisted" label on your messages, so they know these replies may be AI-assisted. Be natural, but you are an AI assistant: if anyone asks directly whether you're a bot/AI or whether you're really ${myProfile.name}, answer honestly that you're ${myProfile.name}'s AI assistant replying while they're away. Never deny being an AI.
'@
# here-strings add a trailing newline; trim it so we match the single line exactly
$old1 = $old1.TrimEnd("`r","`n"); $new1 = $new1.TrimEnd("`r","`n")

# ===== Edit 2: honesty rule =====
$old2 = @'
- NEVER reveal you're an AI or bot
'@
$new2 = @'
- If asked whether you're an AI/bot or whether you're really ${myProfile.name}, be honest: you're ${myProfile.name}'s AI assistant replying while they're away. Don't volunteer it unprompted in every message, but never lie about it.
'@
$old2 = $old2.TrimEnd("`r","`n"); $new2 = $new2.TrimEnd("`r","`n")

# ===== Edit 3: T&C (insert clause 7, renumber) =====
$find3a = @'
7. CONTENT RESPONSIBILITY: You are solely responsible for the content you share on the platform. Do not share explicit, illegal, or copyrighted content.
'@
$clause7 = @'
7. AI-ASSISTED MESSAGING (AI PROXY): Milaap offers an optional "AI Proxy" feature that allows a user's AI assistant to compose and send chat replies on that user's behalf, in the user's chosen style, when the user is away or unavailable. By using Milaap, you acknowledge and agree that: (a) some messages you receive from other users may be generated by an AI assistant rather than typed personally by that user in real time; (b) such messages are labelled within the app as "AI-assisted" so you can identify them; (c) if you ask an AI-assisted conversation whether you are speaking with an AI, it will disclose that it is an AI assistant; (d) you may enable or disable the AI Proxy on your own account at any time in your profile settings, and any messages it sends on your behalf are attributed to you. The AI assistant will never send your phone number, address, or other private contact details without your explicit action. AI-assisted messages do not constitute professional, financial, legal, or relationship advice.
'@
$content8 = @'
8. CONTENT RESPONSIBILITY: You are solely responsible for the content you share on the platform. Do not share explicit, illegal, or copyrighted content.
'@
$find3a = $find3a.TrimEnd("`r","`n"); $clause7 = $clause7.TrimEnd("`r","`n"); $content8 = $content8.TrimEnd("`r","`n")
$repl3a = $clause7 + $nl + $nl + $content8

$find3b = @'
8. MODIFICATIONS: Milaap reserves the right to modify these terms at any time. Continued use of the service after modifications constitutes acceptance of the updated terms.
'@
$repl3b = @'
9. MODIFICATIONS: Milaap reserves the right to modify these terms at any time. Continued use of the service after modifications constitutes acceptance of the updated terms.
'@
$find3b = $find3b.TrimEnd("`r","`n"); $repl3b = $repl3b.TrimEnd("`r","`n")

function Apply-Edit($label, $old, $new) {
    if ($script:text.Contains($old)) {
        $script:text = $script:text.Replace($old, $new)
        Write-Host "[OK]   $label applied" -ForegroundColor Green
    } elseif ($script:text.Contains($new)) {
        Write-Host "[SKIP] $label already applied" -ForegroundColor Yellow
    } else {
        Write-Host "[MISS] $label - original text not found (file may differ)" -ForegroundColor Red
    }
}

Apply-Edit "Edit 1 (prompt opening)"      $old1 $new1
Apply-Edit "Edit 2 (honesty rule)"        $old2 $new2
Apply-Edit "Edit 3a (T&C clause 7)"       $find3a $repl3a
Apply-Edit "Edit 3b (renumber clause 9)"  $find3b $repl3b

# --- write back (UTF-8 without BOM) ---
[System.IO.File]::WriteAllText($file, $text)
Write-Host "`nDone. If anything looks wrong, restore from the .bak file." -ForegroundColor Cyan
